### PR TITLE
Issue #12 : missing some Yunohost functions, added in upgrade

### PR DESCRIPTION
**Pull request by moutonjr**
Please note it has been tested with a running instance of OSJS, but still to be tested on a freshly-installed instance.
The missing file has been forked from : https://github.com/YunoHost-Apps/umap_ynh/blob/master/scripts/.fonctions

-- moutonjr

### CODE REVIEW

**Comment by frju365** [comment]
Thank you ! I agree with you. But, I would prefer doing again the upgrade with the new helpers which are already integrated in Yunohost (core). I will try to find a solution tomorrow.

**Comment by moutonjr** [comment]
Ok no problem then, you can toss my PR.

Regards,

-- Geoff

Le July 19, 2018 4:04:26 PM UTC, frju365 <notifications@github.com> a écrit :
>Thank you ! I agree with you. But, I would prefer doing again the
>upgrade with the new helpers which are already integrated in Yunohost
>(core). I will try to find a solution tomorrow.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/osjs_ynh/pull/14#issuecomment-406329632

-- 
Geoffrey Montel

Envoyé de mon ordiphone, excusez concision et affres du clavier.

**Comment by yalh76** [comment]
no more needed

**Comment by moutonjr** [comment]
Hello, why? New update?

**Comment by yalh76** [comment]
yep https://github.com/YunoHost-Apps/osjs_ynh/pull/18

**Pull request closed without merging**
